defaults: &defaults
  encoding: utf-8
  username: jrae
  password:
  pool: 5
  host: 127.0.0.1
  reconnect: true
  adapter: postgresql

development:
  <<: *defaults
  database: sasc_dev

test: &test
  <<: *defaults
  database: sasc_test
